### ISSUE TITLE
Unable to create Order

### ISSUE THREAD

**Issue by Poissac9** [binance/binance-pay-connector-python#8]
The integration was working perfectly fine for almost a week.

It started returning this error each time my users were trying to pay (creating orders):

{'code': 0, 'msg': "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."}

The code is hosted on heroku

**Comment by alplabin** [comment]
This issue has been addressed in the following forum discussion: https://dev.binance.vision/t/binance-pay-unable-to-create-order/17811/3
